<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<%@ taglib prefix="c" uri="http://java.sun.com/jstl/core" %>
<HTML>
 <HEAD>
 </HEAD>
 <BODY>
 <%//for some strange reason beyond my comprehension, if I put the error message on this page,
   //a page not found error is generated by Tomcat
   //If I redirect to another jsp, with the message, it works. That's the reason for this strange code.%>
 <c:redirect url="/systemFailure.jsp"/>
 </BODY>
</HTML>
