package com.sparrow.domain;

// Generated May 11, 2007 4:25:10 PM by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * Author generated by hbm2java
 */
public class Author implements java.io.Serializable {
  private static final transient Log logger = LogFactory.getLog(Author.class);
  
  public static final String AUTHOR_NAME_SEPERATOR = " ";

  private int authorId;

  private String firstName;

  private String lastName;
  
  private String fullName;

  private Set products = new HashSet(0);

  public Author() {
  }

  public Author(String firstName, String lastName) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.fullName = firstName + " " + lastName;
  }

  public Author(String firstName, String lastName, Set products) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.fullName = firstName + " " + lastName;
    this.products = products;
  }

  public int getAuthorId() {
    return this.authorId;
  }

  private void setAuthorId(int authorId) {
    this.authorId = authorId;
  }

  public String getFirstName() {
    return this.firstName;
  }

  /**
   * Set firstName and also update the fullName.
   * @param firstName
   * @since 1.0
   */
  public void setFirstName(String firstName) {
    this.firstName = firstName;
    //this.setFullName(firstName + " " + getLastName());
  }

  public String getLastName() {
    return this.lastName;
  }

  /**
   * Set lastName and also update the fullName.
   * @param lastName
   * @since 1.0
   */
  public void setLastName(String lastName) {
    this.lastName = lastName;
    //this.setFullName(getFirstName() + " " + lastName);
  }

  public Set getProducts() {
    return this.products;
  }

  public void setProducts(Set products) {
    this.products = products;
  }

  public String getFullName() {
    return fullName;
  }

  /**
   * Full name is updated each time firstName or lastName is updated
   * @param fullName
   * @since 1.0
   */
  public void setFullName(String fullName) {
//    if (!fullName.equals(firstName + " " + lastName)) {
//      String msg = "FullName=" + fullName + 
//                    " does not match firstName + lastName=" + firstName + " " + lastName;
//      logger.error(msg);
//      throw new IllegalStateException(msg);
//    }
    this.fullName = fullName;
    
  }

  /**
   * @see java.lang.Object#toString()
   */
  public String toString() {
    return new ToStringBuilder(this).append("lastName", this.lastName)
                                    .append("firstName", this.firstName)
                                    .append("authorId", this.authorId).toString();
  }

  @Override
  public int hashCode() {
    final int PRIME = 31;
    int result = 1;
    result = PRIME * result + authorId;
    return result;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    final Author other = (Author) obj;
    if (authorId != other.authorId)
      return false;
    return true;
  }
  
  
  

}
