package com.sparrow.domain;

// Generated Jan 17, 2008 6:31:05 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

import com.sparrow.service.payment.PaymentStatusEnum;

/**
 * Bill generated by hbm2java
 */
public class Bill implements java.io.Serializable {

  private int billId;

  private User user;

  private SubscriptionPlan subscriptionPlan;
  
  private Payment payment;
  
  private Set payments = new HashSet();

  private int amount;

  private Date billDate;

  private String status;

  private String comment;
  
  private String description;

  public Bill() {
  }

  public Bill(User user, SubscriptionPlan subscriptionPlan, int amount, Date billDate) {
    this.user = user;
    this.subscriptionPlan = subscriptionPlan;
    this.amount = amount;
    this.billDate = billDate;
  }

  public int getBillId() {
    return this.billId;
  }

  private void setBillId(int billId) {
    this.billId = billId;
  }

  public User getUser() {
    return this.user;
  }

  public void setUser(User user) {
    this.user = user;
  }

  public SubscriptionPlan getSubscriptionPlan() {
    return this.subscriptionPlan;
  }

  public void setSubscriptionPlan(SubscriptionPlan subscriptionPlan) {
    this.subscriptionPlan = subscriptionPlan;
  }
  
  public Payment getPayment() {
    Payment payment = null;
    Iterator itr = payments.iterator();
    while (itr.hasNext()) {
      Payment payment2 = (Payment)itr.next();
      if (PaymentStatusEnum.SUCCESS.getValue().equals(payment2.getStatus())) {
        payment = payment2;
        break;
      }
    }
    return payment;
  }

//  public void setPayment(Payment payment) {
//    this.payment = payment;
//  }

  public int getAmount() {
    return this.amount;
  }

  public void setAmount(int amount) {
    this.amount = amount;
  }

  public Date getBillDate() {
    return this.billDate;
  }

  public void setBillDate(Date billDate) {
    this.billDate = billDate;
  }

  public String getStatus() {
    return this.status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public String getComment() {
    return this.comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Set getPayments() {
    return payments;
  }

  public void setPayments(Set payments) {
    this.payments = payments;
  }
  
  

}
