package com.sparrow.domain;

// Generated May 11, 2007 4:25:10 PM by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

  private int companyId;

  private String companyName;

  private Set products = new HashSet(0);

  public Company() {
  }

  public Company(String companyName) {
    this.companyName = companyName;
  }

  public Company(String companyName, Set products) {
    this.companyName = companyName;
    this.products = products;
  }

  public int getCompanyId() {
    return this.companyId;
  }

  private void setCompanyId(int companyId) {
    this.companyId = companyId;
  }

  public String getCompanyName() {
    return this.companyName;
  }

  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }

  public Set getProducts() {
    return this.products;
  }

  public void setProducts(Set products) {
    this.products = products;
  }

}
