package com.sparrow.domain;

// Generated Aug 6, 2007 3:07:37 PM by Hibernate Tools 3.2.0.b9

/**
 * HomeProduct generated by hbm2java
 */
public class HomeProduct implements java.io.Serializable {

  private int productId;
  
  private Product product;

  private int priority;

  public HomeProduct() {
  }
  
  public HomeProduct(Product product, int priority) {
    //this.productId = product.getProductId();
    this.product = product;
    this.priority = priority;
  }

  public int getProductId() {
    return productId;
  }

  public void setProductId(int productId) {
    this.productId = productId;
  }

  public Product getProduct() {
    return product;
  }
  public void setProduct(Product product) {
    this.product = product;
  }

  public int getPriority() {
    return this.priority;
  }

  public void setPriority(int priority) {
    this.priority = priority;
  }

}
