package com.sparrow.domain;

import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;

/**
 * ProductRequest generated by hbm2java
 */
public class ProductRequest implements java.io.Serializable {

  private Product product;
  private Date addDate;

  public ProductRequest() {
  }

  public ProductRequest(Product product, Date addDate) {
    this.product = product;
    this.addDate = addDate;
  }

  public Product getProduct() {
    return product;
  }

  public void setProduct(Product product) {
    this.product = product;
  }

  public Date getAddDate() {
    return addDate;
  }

  public void setAddDate(Date addDate) {
    this.addDate = addDate;
  }

  @Override
  public int hashCode() {
    final int PRIME = 31;
    int result = 1;
    result = PRIME * result + ((product == null) ? 0 : product.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    final ProductRequest other = (ProductRequest) obj;
    if (product == null) {
      if (other.product != null)
        return false;
    } else if (!product.equals(other.product))
      return false;
    return true;
  }

  
  
  
  

}
