package com.sparrow.domain;

// Generated Sep 21, 2008 10:51:01 PM by Hibernate Tools 3.2.0.b9

/**
 * ProductSearch generated by hbm2java
 */
public class ProductSearch implements java.io.Serializable {

  private int productId;

  private String productName;

  private String productDesc;
  
  private String productIsbn;
  
  private String authorFullName;

  public ProductSearch() {
  }
  
  public ProductSearch(int productId, String productName, String productDesc, String productIsbn, String authorFullName) {
    super();
    this.productId = productId;
    this.productName = productName;
    this.productDesc = productDesc;
    this.productIsbn = productIsbn;
    this.authorFullName = authorFullName;
  }



  public int getProductId() {
    return this.productId;
  }

  public void setProductId(int productId) {
    this.productId = productId;
  }

  public String getAuthorFullName() {
    return authorFullName;
  }

  public void setAuthorFullName(String authorFullName) {
    this.authorFullName = authorFullName;
  }

  public String getProductDesc() {
    return productDesc;
  }

  public void setProductDesc(String productDesc) {
    this.productDesc = productDesc;
  }

  public String getProductIsbn() {
    return productIsbn;
  }

  public void setProductIsbn(String productIsbn) {
    this.productIsbn = productIsbn;
  }

  public String getProductName() {
    return productName;
  }

  public void setProductName(String productName) {
    this.productName = productName;
  }  

}
