package com.sparrow.domain;

// Generated Sep 20, 2008 9:48:31 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * UserNotes generated by hbm2java
 */
public class UserNote implements java.io.Serializable {

  private int userNoteId;

  private Date noteDate;

  private int userId;

  private String note;

  private User addedByUser;
  
  private int priority;

  public UserNote() {
  }

  public UserNote(Date noteDate, int userId, String note, User addedByUser) {
    this.userNoteId = userNoteId;
    this.noteDate = noteDate;
    this.userId = userId;
    this.note = note;
    this.addedByUser = addedByUser;
  }

  public int getUserNoteId() {
    return this.userNoteId;
  }

  private void setUserNoteId(int userNoteId) {
    this.userNoteId = userNoteId;
  }

  public Date getNoteDate() {
    return this.noteDate;
  }

  public void setNoteDate(Date noteDate) {
    this.noteDate = noteDate;
  }

  public int getUserId() {
    return this.userId;
  }

  public void setUserId(int userId) {
    this.userId = userId;
  }

  public String getNote() {
    return this.note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public User getAddedByUser() {
    return this.addedByUser;
  }

  public void setAddedByUser(User addedByUser) {
    this.addedByUser = addedByUser;
  }

  public int getPriority() {
    return priority;
  }

  public void setPriority(int priority) {
    this.priority = priority;
  }
  
}
