package com.sparrow.domain;

// Generated Jun 15, 2007 4:29:09 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * UserProductHistory generated by hbm2java
 */
public class UserProductHistory implements java.io.Serializable {

  private int userProdHistId;

  private User userByUserId;

  private ProductInstance productInstance;
  
  private DeliveryRequest deliveryRequest;

  private User userByCheckoutUserId;

  private User userByReceiveUserId;

  private Date checkoutDate;

  private Date receiveDate;

  private String receiveComment;

  public UserProductHistory() {
  }

  public UserProductHistory(int userProdHistId, User userByUserId,
      ProductInstance productInstance) {
    this.userProdHistId = userProdHistId;
    this.userByUserId = userByUserId;
    this.productInstance = productInstance;
  }

  /**
   * Constructor to create a {@link UserProductHistory} based on existing {@link UserProduct}
   * @param userProduct
   * @since 1.0
   */
  public UserProductHistory(UserProduct userProduct) {
    this.userByUserId = userProduct.getUserByUserId();
    this.productInstance = userProduct.getProductInstance();
    this.userByCheckoutUserId = userProduct.getUserByCheckoutUserId();
    this.checkoutDate = userProduct.getCheckoutDate();
    this.deliveryRequest = userProduct.getDeliveryRequest();
    
  }

  public int getUserProdHistId() {
    return this.userProdHistId;
  }

  public void setUserProdHistId(int userProdHistId) {
    this.userProdHistId = userProdHistId;
  }

  public User getUserByUserId() {
    return this.userByUserId;
  }

  public void setUserByUserId(User userByUserId) {
    this.userByUserId = userByUserId;
  }

  public ProductInstance getProductInstance() {
    return this.productInstance;
  }

  public void setProductInstance(ProductInstance productInstance) {
    this.productInstance = productInstance;
  }

  public DeliveryRequest getDeliveryRequest() {
    return deliveryRequest;
  }

  public void setDeliveryRequest(DeliveryRequest deliveryRequest) {
    this.deliveryRequest = deliveryRequest;
  }

  public User getUserByCheckoutUserId() {
    return this.userByCheckoutUserId;
  }

  public void setUserByCheckoutUserId(User userByCheckoutUserId) {
    this.userByCheckoutUserId = userByCheckoutUserId;
  }

  public User getUserByReceiveUserId() {
    return this.userByReceiveUserId;
  }

  public void setUserByReceiveUserId(User userByReceiveUserId) {
    this.userByReceiveUserId = userByReceiveUserId;
  }

  public Date getCheckoutDate() {
    return this.checkoutDate;
  }

  public void setCheckoutDate(Date checkoutDate) {
    this.checkoutDate = checkoutDate;
  }

  public Date getReceiveDate() {
    return this.receiveDate;
  }

  public void setReceiveDate(Date receiveDate) {
    this.receiveDate = receiveDate;
  }

  public String getReceiveComment() {
    return this.receiveComment;
  }

  public void setReceiveComment(String receiveComment) {
    this.receiveComment = receiveComment;
  }

}
