package com.sparrow.domain;

// Generated May 19, 2007 7:57:54 PM by Hibernate Tools 3.2.0.b9

/**
 * AuthoritiesId generated by hbm2java
 */
public class UserRoleId implements java.io.Serializable {

  private int userId;

  private String role;

  public UserRoleId() {
  }
  
  public UserRoleId(String authority) {
    this.userId = userId;
    this.role = authority;
  }

  public UserRoleId(int userId, String authority) {
    this.userId = userId;
    this.role = authority;
  }

  public int getUserId() {
    return this.userId;
  }

  public void setUserId(int userId) {
    this.userId = userId;
  }

  public String getRole() {
    return this.role;
  }

  public void setRole(String authority) {
    this.role = authority;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof UserRoleId))
      return false;
    UserRoleId castOther = (UserRoleId) other;

    return (this.getUserId() == castOther.getUserId())
        && ((this.getRole() == castOther.getRole()) || (this
            .getRole() != null
            && castOther.getRole() != null && this.getRole().equals(
            castOther.getRole())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + this.getUserId();
    result = 37 * result
        + (getRole() == null ? 0 : this.getRole().hashCode());
    return result;
  }

}
