package com.sparrow.domain;

// Generated May 19, 2007 7:57:54 PM by Hibernate Tools 3.2.0.b9

/**
 * Authorities generated by hbm2java
 */
public class UserRole implements java.io.Serializable {
  
  public static final String ROLE_USER = "ROLE_USER";
  public static final String ROLE_ADMIN = "ROLE_ADMIN";

  private UserRoleId id;

  public UserRole() {
  }

  public UserRole(UserRoleId id) {
    this.id = id;
  }

  public UserRoleId getId() {
    return this.id;
  }

  public void setId(UserRoleId id) {
    this.id = id;
  }

}
